"use client";

/**
 * The off-canvas navigation panel — the app's drawer, one layer above the
 * generated one.
 *
 * Why this file exists: `components/ui/drawer.tsx` is regenerated by
 * `shadcn add`, so a hand-edit there disappears the next time anyone runs it.
 * And it needs an edit. Its backdrop is `bg-black/10`, which over Nocturne's
 * `--color-bg` (#161826) is a barely-perceptible film — the drawn design calls
 * for `--color-neutral-900` at 50%, and a backdrop that does not read as one
 * leaves the page looking broken rather than dimmed.
 *
 * The generated `DrawerContent` renders that backdrop itself and takes no
 * className for it, so the panel is composed here instead of wrapped: the
 * shadcn `DrawerPortal` and `DrawerOverlay` are reused (the overlay with the
 * token colour passed in), and the popup is built from the Base UI parts
 * directly rather than inheriting `DrawerContent`'s bottom-sheet geometry —
 * snap points, swipe stacking and a 75% width this panel does not want.
 *
 * Motion: the slide is a `transition-transform`, disabled outright under
 * `prefers-reduced-motion: reduce`. Nothing else in the repo branches on that
 * media feature yet, so this is the first place it is honoured.
 */

import { Drawer as DrawerPrimitive } from "@base-ui/react/drawer";

import { DrawerOverlay, DrawerPortal } from "@/components/ui/drawer";
import { cn } from "@/lib/utils";

/**
 * The panel itself: full-height, anchored left, 236px wide.
 *
 * Focus is trapped while open and returned to the trigger on close — both come
 * from the Base UI popup, as do the `Esc` and outside-press dismissals. The
 * backdrop below is what makes the outside press reachable.
 */
export function AppDrawerPanel({
  className,
  children,
  ...props
}: DrawerPrimitive.Popup.Props) {
  return (
    <DrawerPortal>
      <DrawerOverlay
        data-slot="app-drawer-overlay"
        className="bg-neutral-900/50 motion-reduce:transition-none"
      />
      <DrawerPrimitive.Viewport className="pointer-events-none fixed inset-0 z-50">
        <DrawerPrimitive.Popup
          data-slot="app-drawer-panel"
          className={cn(
            "pointer-events-auto fixed inset-y-0 left-0 z-50 flex w-59 flex-col bg-card shadow-lg outline-none",
            "transition-transform duration-300 ease-out",
            "data-starting-style:-translate-x-full data-ending-style:-translate-x-full",
            "motion-reduce:transition-none",
            className,
          )}
          {...props}
        >
          <DrawerPrimitive.Content className="flex min-h-0 flex-1 flex-col overflow-y-auto overscroll-contain">
            {children}
          </DrawerPrimitive.Content>
        </DrawerPrimitive.Popup>
      </DrawerPrimitive.Viewport>
    </DrawerPortal>
  );
}

export {
  Drawer as AppDrawer,
  DrawerTrigger as AppDrawerTrigger,
  DrawerTitle as AppDrawerTitle,
} from "@/components/ui/drawer";
